
try {
    funcion_que_no_existe();
} catch (ex) {
    console.log("error detectado: " + ex)
}